# ---- DXVK GLOBAL ----
dxvk.enableAsync = true
dxvk.gplAsyncCache = true
dxvk.enableGraphicsPipelineLibrary = Auto

# ---- FRAME RATE LIMITER ----
dxgi.maxFrameRate = 0
dxgi.syncInterval = 0

# ---- BACKBUFFERS & LATENCY ----
dxgi.maxFrameLatency = 1
d3d11.disableMsaa = True
d3d11.maxTessFactor = 8
d3d11.samplerAnisotropy = 0
d3d11.samplerLodBias = 100000.0

# ---- HUD ----
# dxvk.hud = fps,frametimes

# ---- HDR ----
#dxgi.enableHDR = True
#dxvk.allowFse = True

# ---- CURRENT TESTING ----
d3d11.relaxedBarriers = True
d3d11.relaxedGraphicsBarriers = True
d3d11.cachedDynamicResources = cr
dxvk.tearFree = False
dxvk.latencySleep = True
d3d11.enableContextLock = False
d3d11.invariantPosition = False
dxgi.deferSurfaceCreation = True

